language: python

python:
    - "3.6"

install:
    - pip install -r requirements.txt

before_script:
    - psql -c "CREATE ROLE dianna WITH SUPERUSER LOGIN PASSWORD 'keko';" -U postgres
    - psql -c "CREATE DATABASE storemanager;" -U postgres

script:
    - pytest tests/ --cov=app --cov-report term-missing

after_success:
    - coveralls
   